### ISSUE TITLE
Documentation on staging locally

### ISSUE THREAD

**Issue by kwannoel** [nus-cs2030/1920-s2#7]
Include documentation on how to stage the static site (https://nus-cs2030.github.io/1920-s2/contents/textbook/textbook.html) locally via `README.md`

Users can reach the html page via:
`file:///<PROJECT_ROOT>/_site/contents/textbook/textbook.html`

I believe it is generated by the markdown file:
`<PROJECT_ROOT>/contents/textbook/textbook.md`.

Would be great if the generation process was documented. Thanks!

**Comment by seanlowjk** [comment]
Hi! 

You have a very good point there, 

I will add it hopefully by the end of today or tomorrow, so for those interested can set up their own staging environment on their own computers! 

Thank you for the issue and will update here once this is done.

**Comment by seanlowjk** [comment]
I have updated it in this link [here](https://github.com/nus-cs2030/1920-s2/commit/19745eec5e389e42f629d309e8cc177e982f4440)!

Thanks for the feedback
